/**
 * FinancialProfileDashboard - Example Component
 *
 * This is an example of how to build a feature using the FinancePro architecture:
 * - Uses Orval-generated hooks for API calls
 * - Uses Zod schemas for validation
 * - Follows React best practices (hooks, composition, TypeScript)
 * - Demonstrates reusable patterns
 *
 * TODO: Move to features/dashboard/ when implementing full dashboard
 */

import React, { useState } from 'react';
import {
  useListProfilesApiV1ProfilesGet,
  useCreateProfileApiV1ProfilesPost,
  useDeleteProfileApiV1ProfilesIdDelete
} from '@/api/generated/financial_profiles/financial_profiles';
import type {
  FinancialProfileCreate,
  FinancialProfileResponse
} from '@/api/generated/models';

/**
 * Main Dashboard Component
 *
 * Shows list of financial profiles and allows creating new ones
 */
export const FinancialProfileDashboard: React.FC = () => {
  // State
  const [isCreating, setIsCreating] = useState(false);

  // API Hooks (auto-generated by Orval)
  const {
    data: profilesData,
    isLoading,
    error,
    refetch
  } = useListProfilesApiV1ProfilesGet();

  const createProfile = useCreateProfileApiV1ProfilesPost();
  const deleteProfile = useDeleteProfileApiV1ProfilesIdDelete();

  // Handlers
  const handleCreate = async (profileData: FinancialProfileCreate) => {
    try {
      await createProfile.mutateAsync({ data: profileData });
      refetch(); // Refresh list after creation
      setIsCreating(false);
    } catch (err) {
      console.error('Failed to create profile:', err);
    }
  };

  const handleDelete = async (profileId: string) => {
    if (!confirm('Are you sure you want to delete this profile?')) return;

    try {
      await deleteProfile.mutateAsync({ id: profileId });
      refetch(); // Refresh list after deletion
    } catch (err) {
      console.error('Failed to delete profile:', err);
    }
  };

  // Loading state
  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-lg">Loading profiles...</div>
      </div>
    );
  }

  // Error state
  if (error) {
    return (
      <div className="bg-red-50 border border-red-200 rounded p-4">
        <h3 className="text-red-800 font-semibold">Error loading profiles</h3>
        <p className="text-red-600">{error.message}</p>
      </div>
    );
  }

  const profiles = profilesData?.items || [];

  return (
    <div className="container mx-auto p-6">
      {/* Header */}
      <div className="flex justify-between items-center mb-8">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Financial Profiles</h1>
          <p className="text-gray-600 mt-1">
            Manage your personal, family, and business finances separately
          </p>
        </div>
        <button
          onClick={() => setIsCreating(true)}
          className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg font-medium transition-colors"
        >
          + New Profile
        </button>
      </div>

      {/* Profile List */}
      {profiles.length === 0 ? (
        <div className="bg-gray-50 border-2 border-dashed border-gray-300 rounded-lg p-12 text-center">
          <h3 className="text-lg font-semibold text-gray-700 mb-2">
            No financial profiles yet
          </h3>
          <p className="text-gray-500 mb-4">
            Create your first profile to start managing your finances
          </p>
          <button
            onClick={() => setIsCreating(true)}
            className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg font-medium transition-colors"
          >
            Create First Profile
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {profiles.map((profile) => (
            <ProfileCard
              key={profile.id}
              profile={profile}
              onDelete={() => handleDelete(profile.id)}
            />
          ))}
        </div>
      )}

      {/* Create Profile Modal */}
      {isCreating && (
        <CreateProfileModal
          onClose={() => setIsCreating(false)}
          onCreate={handleCreate}
          isLoading={createProfile.isPending}
        />
      )}
    </div>
  );
};

/**
 * Profile Card Component
 *
 * Displays a single financial profile with actions
 */
interface ProfileCardProps {
  profile: FinancialProfileResponse;
  onDelete: () => void;
}

const ProfileCard: React.FC<ProfileCardProps> = ({ profile, onDelete }) => {
  const profileTypeLabels = {
    personal: 'Personal',
    family: 'Family',
    business: 'Business',
  };

  const profileTypeColors = {
    personal: 'bg-blue-100 text-blue-800',
    family: 'bg-green-100 text-green-800',
    business: 'bg-purple-100 text-purple-800',
  };

  return (
    <div className="bg-white border border-gray-200 rounded-lg p-6 hover:shadow-lg transition-shadow">
      {/* Header */}
      <div className="flex justify-between items-start mb-4">
        <div>
          <h3 className="text-xl font-semibold text-gray-900">{profile.name}</h3>
          {profile.description && (
            <p className="text-gray-600 text-sm mt-1">{profile.description}</p>
          )}
        </div>
        <span className={`px-2 py-1 rounded text-xs font-medium ${profileTypeColors[profile.profile_type]}`}>
          {profileTypeLabels[profile.profile_type]}
        </span>
      </div>

      {/* Metadata */}
      <div className="space-y-2 mb-4">
        <div className="flex justify-between text-sm">
          <span className="text-gray-500">Currency:</span>
          <span className="font-medium">{profile.default_currency}</span>
        </div>
        <div className="flex justify-between text-sm">
          <span className="text-gray-500">Status:</span>
          <span className={profile.is_available ? 'text-green-600' : 'text-red-600'}>
            {profile.is_available ? '● Available' : '○ Unavailable'}
          </span>
        </div>
        <div className="flex justify-between text-sm">
          <span className="text-gray-500">Created:</span>
          <span>{new Date(profile.created_at).toLocaleDateString()}</span>
        </div>
      </div>

      {/* Actions */}
      <div className="flex gap-2 pt-4 border-t border-gray-200">
        <button
          onClick={() => {/* Navigate to profile */}}
          className="flex-1 bg-blue-50 hover:bg-blue-100 text-blue-700 px-4 py-2 rounded font-medium transition-colors"
        >
          View
        </button>
        <button
          onClick={onDelete}
          className="bg-red-50 hover:bg-red-100 text-red-700 px-4 py-2 rounded font-medium transition-colors"
        >
          Delete
        </button>
      </div>
    </div>
  );
};

/**
 * Create Profile Modal Component
 *
 * Form for creating a new financial profile with validation
 */
interface CreateProfileModalProps {
  onClose: () => void;
  onCreate: (data: FinancialProfileCreate) => void;
  isLoading: boolean;
}

const CreateProfileModal: React.FC<CreateProfileModalProps> = ({
  onClose,
  onCreate,
  isLoading
}) => {
  const [formData, setFormData] = useState<FinancialProfileCreate>({
    name: '',
    description: '',
    profile_type: 'personal',
    default_currency: 'EUR',
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onCreate(formData);
  };

  const handleChange = (field: keyof FinancialProfileCreate, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-lg shadow-xl max-w-md w-full">
        {/* Header */}
        <div className="px-6 py-4 border-b border-gray-200">
          <h2 className="text-xl font-semibold text-gray-900">Create Financial Profile</h2>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="px-6 py-4 space-y-4">
          {/* Name */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Name *
            </label>
            <input
              type="text"
              required
              value={formData.name}
              onChange={(e) => handleChange('name', e.target.value)}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              placeholder="e.g., Personal Finances"
            />
          </div>

          {/* Description */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Description
            </label>
            <textarea
              value={formData.description || ''}
              onChange={(e) => handleChange('description', e.target.value)}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              rows={3}
              placeholder="Optional description..."
            />
          </div>

          {/* Profile Type */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Type *
            </label>
            <select
              required
              value={formData.profile_type}
              onChange={(e) => handleChange('profile_type', e.target.value as any)}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            >
              <option value="personal">Personal</option>
              <option value="family">Family</option>
              <option value="business">Business</option>
            </select>
          </div>

          {/* Currency */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Default Currency *
            </label>
            <select
              required
              value={formData.default_currency}
              onChange={(e) => handleChange('default_currency', e.target.value)}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            >
              <option value="EUR">EUR - Euro</option>
              <option value="USD">USD - US Dollar</option>
              <option value="GBP">GBP - British Pound</option>
              <option value="CHF">CHF - Swiss Franc</option>
            </select>
          </div>

          {/* Actions */}
          <div className="flex gap-2 pt-4">
            <button
              type="button"
              onClick={onClose}
              disabled={isLoading}
              className="flex-1 border border-gray-300 hover:bg-gray-50 text-gray-700 px-4 py-2 rounded-lg font-medium transition-colors disabled:opacity-50"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={isLoading}
              className="flex-1 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg font-medium transition-colors disabled:opacity-50"
            >
              {isLoading ? 'Creating...' : 'Create Profile'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default FinancialProfileDashboard;
