/**
 * Optimization feature types
 *
 * All types for the optimization feature are defined here.
 * Since this is a frontend-only feature with mock API, types are defined
 * manually rather than being generated from Orval.
 */

// ============================================================================
// Utility Types
// ============================================================================

export type SuggestionCategory =
  | 'savings'
  | 'subscriptions'
  | 'alternatives'
  | 'timing'
  | 'cashflow';

export type SuggestionPriority = 'low' | 'medium' | 'high' | 'critical';

export type WasteType =
  | 'unused_subscription'
  | 'duplicate_service'
  | 'high_cost_low_usage'
  | 'better_alternative';

export type DifficultyLevel = 'easy' | 'medium' | 'hard';

export type ImpactLevel = 'low' | 'medium' | 'high';

export type StrategyStatus = 'suggested' | 'active' | 'completed' | 'abandoned';

export type SuggestionStatus = 'active' | 'implemented' | 'dismissed';

export type UsageFrequency = 'never' | 'rarely' | 'occasionally' | 'frequently';

export type BillingFrequency = 'monthly' | 'yearly' | 'quarterly';

// ============================================================================
// Core Types
// ============================================================================

/**
 * Optimization suggestion generated by AI analysis
 */
export interface OptimizationSuggestion {
  id: string;
  title: string;
  description: string;
  category: SuggestionCategory;
  priority: SuggestionPriority;
  potentialSavings: number;
  monthlySavings: number;
  confidence: number; // 0-1
  aiExplanation: string;
  actionSteps: string[];
  relatedTransactions?: string[];
  status: SuggestionStatus;
  createdAt: string;
  implementedAt?: string;
}

/**
 * Detection of wasteful spending patterns
 */
export interface WasteDetection {
  id: string;
  type: WasteType;
  merchantName: string;
  category: string;
  subscriptionAmount: number;
  frequency: BillingFrequency;
  lastUsage?: string;
  usageCount: number;
  usageFrequency: UsageFrequency;
  costPerUse: number;
  monthlyCost: number;
  detectedAt: string;
  recommendation: string;
  potentialSaving: number;
}

/**
 * Duplicate service detection
 */
export interface DuplicateService {
  id: string;
  services: {
    merchantName: string;
    amount: number;
    frequency: string;
  }[];
  category: string;
  totalMonthlyCost: number;
  recommendation: string;
  potentialSaving: number;
}

/**
 * Step in a savings strategy
 */
export interface StrategyStep {
  order: number;
  description: string;
  completed: boolean;
}

/**
 * Projected savings for a strategy
 */
export interface ProjectedSavings {
  monthly: number;
  yearly: number;
}

/**
 * Personalized savings strategy
 */
export interface SavingsStrategy {
  id: string;
  title: string;
  description: string;
  targetCategory?: string;
  targetAmount: number;
  timeframe: 'weekly' | 'monthly' | 'quarterly' | 'yearly';
  difficulty: DifficultyLevel;
  impact: ImpactLevel;
  steps: StrategyStep[];
  projectedSavings: ProjectedSavings;
  actualSavings?: number;
  startDate?: string;
  status: StrategyStatus;
}

/**
 * Impact tracking for implemented suggestions
 */
export interface OptimizationImpact {
  suggestionId: string;
  implementedAt: string;
  expectedSavings: number;
  actualSavings: number;
  accuracy: number; // percentage
  verified: boolean;
  notes?: string;
}

/**
 * Waste detection summary
 */
export interface WasteDetectedSummary {
  unusedSubscriptions: number;
  duplicateServices: number;
  totalWastedAmount: number;
}

/**
 * Overview of optimization opportunities
 */
export interface OptimizationOverview {
  totalPotentialSavings: number;
  monthlySavingsOpportunity: number;
  activeSuggestions: number;
  implementedSuggestions: number;
  totalSavedToDate: number;
  topCategory: string;
  averageAccuracy: number;
  wasteDetected: WasteDetectedSummary;
}

/**
 * Recommended alternative service/provider
 */
export interface AlternativeRecommendation {
  id: string;
  currentMerchant: string;
  currentAmount: number;
  suggestedMerchant: string;
  suggestedAmount: number;
  category: string;
  monthlySavings: number;
  yearlyProjection: number;
  qualityScore: number; // 0-100
  reason: string;
  pros: string[];
  cons: string[];
}

/**
 * Current cash flow pattern analysis
 */
export interface CashFlowPattern {
  problematicPeriod: string;
  avgBalance: number;
  minBalance: number;
}

/**
 * Suggested cash flow pattern improvements
 */
export interface SuggestedCashFlowPattern {
  recommendations: string[];
  expectedMinBalance: number;
  improvement: number; // percentage
}

/**
 * Cash flow optimization implementation details
 */
export interface CashFlowImplementation {
  steps: string[];
  difficulty: DifficultyLevel;
}

/**
 * Cash flow optimization suggestion
 */
export interface CashFlowOptimization {
  id: string;
  title: string;
  description: string;
  currentPattern: CashFlowPattern;
  suggestedPattern: SuggestedCashFlowPattern;
  implementation: CashFlowImplementation;
}

// ============================================================================
// Filter Types
// ============================================================================

/**
 * Filters for optimization queries
 */
export interface OptimizationFilters {
  profileId?: string;
  dateFrom?: string;
  dateTo?: string;
  categories?: string[];
  minSavings?: number;
}

// ============================================================================
// Dashboard Types
// ============================================================================

/**
 * Complete optimization dashboard data
 */
export interface OptimizationDashboard {
  overview: OptimizationOverview;
  suggestions: OptimizationSuggestion[];
  wasteDetections: WasteDetection[];
  duplicateServices: DuplicateService[];
  strategies: SavingsStrategy[];
  alternatives: AlternativeRecommendation[];
  cashFlowOptimizations: CashFlowOptimization[];
}
