"""Add accounts, categories, transactions, budgets tables

Revision ID: b4bc8b67e15d
Revises: 72b0531659f0
Create Date: 2025-11-02 17:22:23.460289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4bc8b67e15d'
down_revision: Union[str, None] = '72b0531659f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
